### ISSUE TITLE
No idea what I did wrong...

### ISSUE THREAD

**Issue by freshkitty** [luca28pet/AdvancedKits#53]
[kits.zip](https://github.com/luca28pet/AdvancedKits/files/256096/kits.zip)

This is my kits file, I also made sure that pureperms was correct, but when my players type /kit there are no kits listed. Ive tried practically everything I can think of, but I can't seem to do this right.

**Comment by freshkitty** [comment]
This was also in my console if it helps...

[22:17:40] [Server thread/INFO]: Enabling AdvancedKits v5.0b1
 
Warning: yaml_parse_file(): parsing error encountered during parsing: did not find expected key (line 77, column 44), context while parsing a block mapping (line 63, column 3) in phar:///home/tcagame_svc1287/samd/1287/plugins/AdvancedKits.phar/src/AdvancedKits/Main.php on line 78
 
Warning: Invalid argument supplied for foreach() in phar:///home/tcagame_svc1287/samd/1287/plugins/AdvancedKits.phar/src/AdvancedKits/Main.php on line 86
 
Warning: Invalid argument supplied for foreach() in phar:///home/tcagame_svc1287/samd/1287/plugins/AdvancedKits.phar/src/AdvancedKits/Main.php on line 80

**Comment by luca28pet** [comment]
On line 77 you have:
  - "tell {player} You have recieved kit  "Recruit" and regeneration for 3 minutes!"

This is wrong because you cannot use double brackets inside other double brackets in a yaml file
Try instead
  - "tell {player} You have recieved kit  'Recruit' and regeneration for 3 minutes!"
